test

diff --git a/.github/workflows/go_build.yaml b/.github/workflows/go_build.yaml
--- a/.github/workflows/go_build.yaml
+++ b/.github/workflows/go_build.yaml
@@ -92,6 +92,7 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    if: (github.ref == 'refs/heads/development') || (github.ref == 'refs/heads/main')  || (github.ref == 'refs/heads/master') || github.event_name == 'pull_request'
     name: test and linters
     outputs:
       sha: ${{ steps.output-sha.outputs.sha }}
@@ -197,17 +198,65 @@ jobs:
         run: |
           ${{ inputs.DEPENDENCIES_COMMAND }}
 
+#      - name: golangci-lint
+#        uses: golangci/golangci-lint-action@v3
+#        with:
+#          version: v1.54.2
+#          args: --timeout 8m
+#          skip-pkg-cache: true
+#          skip-build-cache: true
 
+
+#      - name: Test
+#        run: |
+#          mkdir -p temp/build
+#          GOFR_ENV=test go test ./... -count=1 -v -coverprofile temp/cover.out -coverpkg=./...
+#          cat temp/cover.out | grep -v "mock_interface" | grep -v "migrations" > temp/coverage.out
+#
+#      - name: Test Coverage report
+#        run: |
+#          go tool cover -func=temp/coverage.out | tee temp/c.out
+#
+#      - name: Generate and Commit Coverage Badge
+#        if: (github.event_name == 'push') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
+#        run: |
+#          go install github.com/AlexBeauchemin/gobadge@latest
+#          gobadge -filename=temp/c.out -target=$(pwd)/README.md
+#          git config --global user.email "action@github.com" && git config --global user.name "GitHub-Action"
+#          git config --global --add safe.directory /__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})
+#          git diff --quiet --exit-code README.md || git commit README.md -m "updating coverage in README.md"
+#
+#      - name: Push Coverage Badge
+#        if: (github.event_name == 'push') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
+#        uses: ad-m/github-push-action@master
+#        with:
+#          github_token: ${{ github.token }}
+#          branch: ${{github.ref}}
 
       - id: output-sha
         run: |
-          if [ "push" = 'push' ] && [ \( "${{ github.ref }}" = 'refs/heads/main' \) -o \( "${{ github.ref }}" = 'refs/heads/main' \) ]; then
+          if [ "push" = 'push' ] && [ \( "${{ github.ref }}" = 'refs/heads/main' \) -o \( "${{ github.ref }}" = 'refs/heads/master' \) ]; then
             sha=$(git rev-parse HEAD)
           else
             sha="${{ github.sha }}"
           fi
           echo "$sha"
           echo "sha=$sha" >> "$GITHUB_OUTPUT"
+
+#      - name: Coverage Quality Gate
+#        run: |
+#          echo "Quality Gate: checking test coverage is above threshold ..."
+#          echo "Threshold             : ${{ inputs.TESTCOVERAGE_THRESHOLD }}%"
+#          totalCoverage=`go tool cover -func=temp/coverage.out | grep 'total:' | grep -Eo '[0-9]+\.[0-9]+'`
+#          echo "Current test coverage : $totalCoverage %"
+#          totalInt=${totalCoverage%.*}
+#          if [ "$totalInt" -ge "${{ inputs.TESTCOVERAGE_THRESHOLD }}" ]; then
+#              echo "OK"
+#          else
+#              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+#              echo "Failed"
+#              exit 1
+#          fi
 
       - name: Run Server
         if: ${{ inputs.POSTMAN_ENABLED }}
