used existing image

diff --git a/.github/workflows/stage.yaml b/.github/workflows/stage.yaml
--- a/.github/workflows/stage.yaml
+++ b/.github/workflows/stage.yaml
@@ -16,123 +16,123 @@ env:
   artifact_directory: inventory-func
 
 jobs:
-#  build:
-#    name: 🧪 Unit Tests and 🔨 Build
-#    runs-on: ubuntu-latest
+  build:
+    name: 🧪 Unit Tests and 🔨 Build
+    runs-on: ubuntu-latest
+
+    services:
+      postgres:
+        image: postgres:15.1
+        ports:
+          - "5432:5432"
+        env:
+          POSTGRES_PASSWORD: password
+          POSTGRES_USER: postgres
+          POSTGRES_DB: health-check
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+
+    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push')
+
+    steps:
+      - name: Set up Go 1.21
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.21
+          id: Go
+
+      - name: Checkout code into go module directory
+        uses: actions/checkout@v2
+
+      - name: Get dependencies
+        run: |
+          git config --global url."https://x-oauth-basic@github.com/".insteadOf "https://github.com/"
+          git config --global http.sslVerify false
+          go mod download
+
+      - name: Test
+        run: |
+          mkdir -p $artifact_directory/build
+          go test ./... -count=1 -v -coverprofile $artifact_directory/cover.out -coverpkg=./...
+          cat $artifact_directory/cover.out | grep -v "mock_interface" | grep -v "migrations" > $artifact_directory/coverage.out
+
+      - name: Test Coverage report
+        run: |
+          go tool cover -func=$artifact_directory/coverage.out | tee $artifact_directory/c.out
+
+#      - name: Generate and Commit Coverage Badge
+#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
+#        run: |
+#          go install github.com/AlexBeauchemin/gobadge@latest
+#          gobadge -filename=$artifact_directory/c.out -target=$(pwd)/README.md
+#          git config --local user.email "action@github.com" && git config --local user.name "GitHub-Action"
+#          git diff --quiet --exit-code README.md || git commit README.md -m "updating coverage in README.md"
 #
-#    services:
-#      postgres:
-#        image: postgres:15.1
-#        ports:
-#          - "5432:5432"
+#      - name: Push Coverage Badge
+#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
+#        uses: ad-m/github-push-action@master
+#        with:
+#          github_token: ${{ github.token }}
+#          branch: ${{github.ref}}
+#
+#      - name: Coverage Quality Gate
 #        env:
-#          POSTGRES_PASSWORD: password
-#          POSTGRES_USER: postgres
-#          POSTGRES_DB: health-check
-#        options: >-
-#          --health-cmd pg_isready
-#          --health-interval 10s
-#          --health-timeout 5s
-#          --health-retries 5
+#          TESTCOVERAGE_THRESHOLD: 10
+#        run: |
+#          echo "Quality Gate: checking test coverage is above threshold ..."
+#          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+#          totalCoverage=`go tool cover -func=$artifact_directory/coverage.out | grep 'total:' | grep -Eo '[0-9]+\.[0-9]+'`
+#          echo "Current test coverage : $totalCoverage %"
+#          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+#              echo "OK"
+#          else
+#              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+#              echo "Failed"
+#              exit 1
+#          fi
+
+      - name: Make Directory
+        run: mkdir build
+
+      - name: Build
+        run: |
+          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main
+
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: artifacts
+          path: main
+
+#  code_quality:
+#    name: 🎖 Code Quality
+#    runs-on: ubuntu-latest
 #
 #    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push')
 #
 #    steps:
-#      - name: Set up Go 1.21
+#      - name: Check out code into the Go module directory
+#        uses: actions/checkout@v3
+#
+#      - name: Set up Go 1.19
 #        uses: actions/setup-go@v2
 #        with:
-#          go-version: 1.21
-#          id: Go
+#          go-version: 1.19
+#        id: go
 #
-#      - name: Checkout code into go module directory
-#        uses: actions/checkout@v2
-#
-#      - name: Get dependencies
+#      - name: Setup Git
 #        run: |
-#          git config --global url."https://x-oauth-basic@github.com/".insteadOf "https://github.com/"
+#          git config --global url."https://${{ secrets.DEV_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
 #          git config --global http.sslVerify false
-#          go mod download
 #
-#      - name: Test
-#        run: |
-#          mkdir -p $artifact_directory/build
-#          go test ./... -count=1 -v -coverprofile $artifact_directory/cover.out -coverpkg=./...
-#          cat $artifact_directory/cover.out | grep -v "mock_interface" | grep -v "migrations" > $artifact_directory/coverage.out
-#
-#      - name: Test Coverage report
-#        run: |
-#          go tool cover -func=$artifact_directory/coverage.out | tee $artifact_directory/c.out
-#
-##      - name: Generate and Commit Coverage Badge
-##        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
-##        run: |
-##          go install github.com/AlexBeauchemin/gobadge@latest
-##          gobadge -filename=$artifact_directory/c.out -target=$(pwd)/README.md
-##          git config --local user.email "action@github.com" && git config --local user.name "GitHub-Action"
-##          git diff --quiet --exit-code README.md || git commit README.md -m "updating coverage in README.md"
-##
-##      - name: Push Coverage Badge
-##        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
-##        uses: ad-m/github-push-action@master
-##        with:
-##          github_token: ${{ github.token }}
-##          branch: ${{github.ref}}
-##
-##      - name: Coverage Quality Gate
-##        env:
-##          TESTCOVERAGE_THRESHOLD: 10
-##        run: |
-##          echo "Quality Gate: checking test coverage is above threshold ..."
-##          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
-##          totalCoverage=`go tool cover -func=$artifact_directory/coverage.out | grep 'total:' | grep -Eo '[0-9]+\.[0-9]+'`
-##          echo "Current test coverage : $totalCoverage %"
-##          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
-##              echo "OK"
-##          else
-##              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-##              echo "Failed"
-##              exit 1
-##          fi
-#
-#      - name: Make Directory
-#        run: mkdir build
-#
-#      - name: Build
-#        run: |
-#          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main
-#
-#      - name: Upload Artifacts
-#        uses: actions/upload-artifact@v2
+#      - name: golangci-lint
+#        uses: golangci/golangci-lint-action@v3
 #        with:
-#          name: artifacts
-#          path: main
-#
-##  code_quality:
-##    name: 🎖 Code Quality
-##    runs-on: ubuntu-latest
-##
-##    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push')
-##
-##    steps:
-##      - name: Check out code into the Go module directory
-##        uses: actions/checkout@v3
-##
-##      - name: Set up Go 1.19
-##        uses: actions/setup-go@v2
-##        with:
-##          go-version: 1.19
-##        id: go
-##
-##      - name: Setup Git
-##        run: |
-##          git config --global url."https://${{ secrets.DEV_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
-##          git config --global http.sslVerify false
-##
-##      - name: golangci-lint
-##        uses: golangci/golangci-lint-action@v3
-##        with:
-##          version: v1.52.2
-##          args: --timeout 8m
+#          version: v1.52.2
+#          args: --timeout 8m
 #
 #  dockerize:
 #    runs-on: ubuntu-latest
@@ -175,7 +175,6 @@ jobs:
 
   deployment:
     runs-on: ubuntu-latest
-    needs: dockerize
     name: Deploy to Stage
     env:
       image: ${{needs.dockerize.outputs.image}}
